name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:

    - uses: 'actions/checkout@v2'

    - uses: 'actions/setup-python@v2'
      with:
        python-version: '3.8'

    - name: yamlllint
      run: |
        pip install yamllint==1.27.1
        yamllint .

    - name: cfn-lint
      run: |
        pip install cfn-lint==0.62.0
        cfn-lint -i W2001 W4002 W6001 -t '**/*.yaml'

    - name: license
      run: |
        find . -type f -name '*.yaml' | while read file; do set -ex && grep -q 'LICENSE-2.0' "$file"; done;

