name: CI

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/aws-cf-templates/aws-cf-templates/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'

    - uses: 'actions/checkout@v2'

    - run: touch starting_build_uses13_13
    - run: rm starting_build_uses13_13
    - uses: 'actions/setup-python@v2'
      with:
        python-version: '3.8'

    - run: touch starting_build_yamlllint_17
    - run: rm starting_build_yamlllint_17
    - name: yamlllint
      run: |
        pip install yamllint==1.27.1
        yamllint .

    - run: touch starting_build_cfnlint_22
    - run: rm starting_build_cfnlint_22
    - name: cfn-lint
      run: |
        pip install cfn-lint==0.62.0
        cfn-lint -i W2001 W4002 W6001 -t '**/*.yaml'

    - run: touch starting_build_license_27
    - run: rm starting_build_license_27
    - name: license
      run: |
        find . -type f -name '*.yaml' | while read file; do set -ex && grep -q 'LICENSE-2.0' "$file"; done;
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - run: cp /home/runner/inotify-logs.csv /home/runner/work/aws-cf-templates/aws-cf-templates/optimizing-ci-builds-ci-analysis/
      if: always()
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'optimizing-ci-builds'
        destination-repository-name: 'ci-analyzes'
        target-directory: 'aws-cf-templates/1668000559/.github/workflows/ci/build'

